# Generated by Django 5.2.8 on 2025-11-20 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Carnet',
                'verbose_name_plural': 'Tipos de Carnet',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.licensetype', verbose_name='Tipo de Carnet')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta')], max_length=10, verbose_name='Método de Pago')),
                ('date_paid', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Importe')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('description', models.CharField(default='Bono de clases prácticas', max_length=200, verbose_name='Descripción')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='students.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['-date_created'],
            },
        ),
    ]
