# Generated by Django 5.2.8 on 2025-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-date_created'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AddField(
            model_name='voucher',
            name='concept_type',
            field=models.CharField(choices=[('RENEWAL', 'Renovación de carnet'), ('PRACTICAL_EXAM', 'Examen práctico'), ('THEORY_EXAM', 'Examen teórico'), ('REGISTRATION', 'Inscripción'), ('PRACTICE_90', "Práctica 90'"), ('PRACTICE_60', "Práctica 60'"), ('PRACTICE_45', "Práctica 45'"), ('PRACTICE_30', "Práctica 30'"), ('OTHER', 'Otros')], default='PRACTICE_90', max_length=20, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción adicional'),
        ),
    ]
