# Generated by Django 5.2.8 on 2025-11-20 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_voucher_options_voucher_concept_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], max_length=10, verbose_name='Acción')),
                ('entity_type', models.CharField(choices=[('STUDENT', 'Alumno'), ('VOUCHER', 'Cargo'), ('PAYMENT', 'Pago'), ('USER', 'Usuario')], max_length=10, verbose_name='Tipo de entidad')),
                ('entity_id', models.IntegerField(help_text='ID del objeto afectado', verbose_name='ID de entidad')),
                ('entity_name', models.CharField(help_text='Nombre o descripción del objeto afectado', max_length=200, verbose_name='Nombre de entidad')),
                ('description', models.TextField(help_text='Descripción detallada de la acción', verbose_name='Descripción')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='students_au_timesta_12f4cf_idx'), models.Index(fields=['user', '-timestamp'], name='students_au_user_id_233886_idx'), models.Index(fields=['entity_type', 'entity_id'], name='students_au_entity__476a38_idx')],
            },
        ),
    ]
