# Generated by Django 5.2.8 on 2025-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_created_by_voucher_created_by_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Recibo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida del recibo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='upload_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token de subida'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='concept_type',
            field=models.CharField(choices=[('RENEWAL', 'Renovación de carnet'), ('PRACTICAL_EXAM', 'Examen práctico'), ('THEORY_EXAM', 'Examen teórico'), ('REGISTRATION', 'Inscripción'), ('PRACTICE_90', "Práctica 90'"), ('PRACTICE_60', "Práctica 60'"), ('PRACTICE_45', "Práctica 45'"), ('PRACTICE_30', "Práctica 30'"), ('BONUS_5_PRACTICES', "Bono 5 Prácticas 90'"), ('OTHER', 'Otros')], default='PRACTICE_90', max_length=20, verbose_name='Concepto'),
        ),
    ]
