# Generated by Django 5.2.8 on 2025-11-25 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_payment_receipt_payment_receipt_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Coche'), ('MOTORCYCLE', 'Moto'), ('TRUCK', 'Camión'), ('TRAILER', 'Tráiler')], default='CAR', max_length=20, verbose_name='Tipo de vehículo')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de alta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('OIL_CHANGE', 'Cambio de aceite'), ('TIRE_CHANGE', 'Cambio de neumáticos'), ('BRAKE_CHECK', 'Revisión de frenos'), ('GENERAL_REVIEW', 'Revisión general'), ('ITV', 'ITV'), ('REPAIR', 'Reparación'), ('CLEANING', 'Limpieza'), ('FUEL', 'Combustible'), ('INSURANCE', 'Seguro'), ('OTHER', 'Otros')], max_length=20, verbose_name='Tipo de mantenimiento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Marca (repuesto/producto)')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modelo (repuesto/producto)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coste')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de mantenimiento')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='students.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-maintenance_date', '-date_created'],
            },
        ),
    ]
