# Generated by Django 5.2.8 on 2025-11-25 12:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_vehicle_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(choices=[(90, 'Práctica 90 minutos'), (60, 'Práctica 60 minutos'), (45, 'Práctica 45 minutos'), (30, 'Práctica 30 minutos')], default=90, verbose_name='Duración (minutos)')),
                ('practice_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la práctica')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Facturada en bono')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('billed_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices_included', to='students.voucher', verbose_name='Bono asociado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='students.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
                'ordering': ['-practice_date', '-date_created'],
            },
        ),
    ]
