# Generated by Django 5.2.8 on 2025-11-27 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('client_dni', models.CharField(max_length=20, verbose_name='DNI del cliente')),
                ('client_address', models.TextField(blank=True, verbose_name='Dirección del cliente')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base imponible')),
                ('iva_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='students.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-date_issued'],
            },
        ),
    ]
