# Generated by Django 5.2.8 on 2025-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_invoice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expedition_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de expediente'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='concept_type',
            field=models.CharField(choices=[('RENEWAL', 'Renovación de carnet'), ('PRACTICAL_EXAM', 'Examen práctico'), ('THEORY_EXAM', 'Examen teórico'), ('REGISTRATION', 'Inscripción'), ('PRACTICE_90', "Práctica 90'"), ('PRACTICE_60', "Práctica 60'"), ('PRACTICE_45', "Práctica 45'"), ('PRACTICE_30', "Práctica 30'"), ('BONUS_5_PRACTICES', "Bono 5 Prácticas 90'"), ('BONUS_DISCOUNT', "Descuento Bono 450'"), ('OTHER', 'Otros')], default='PRACTICE_90', max_length=20, verbose_name='Concepto'),
        ),
    ]
