# Generated by Django 5.2.8 on 2025-12-30 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_expedition_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, default='VALENCIA', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='student',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle/Dirección'),
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('fecha', models.DateField(verbose_name='Fecha de factura')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'T1'), (2, 'T2'), (3, 'T3'), (4, 'T4')], verbose_name='Trimestre')),
                ('year', models.PositiveIntegerField(verbose_name='Año fiscal')),
                ('curso', models.CharField(choices=[('AM', 'AM - Ciclomotores'), ('A1', 'A1 - Motocicletas hasta 125cc'), ('A2', 'A2 - Motocicletas hasta 35kW'), ('A', 'A - Motocicletas sin límite'), ('B', 'B - Automóviles'), ('C', 'C - Camiones'), ('C+E', 'C+E - Camión con remolque')], max_length=5, verbose_name='Tipo de curso')),
                ('has_tasa_basica', models.BooleanField(default=False, verbose_name='Incluye Tasa Básica')),
                ('has_tasa_a', models.BooleanField(default=False, verbose_name='Incluye Tasa A (motocicletas)')),
                ('has_traslado', models.BooleanField(default=False, verbose_name='Incluye Traslado expediente')),
                ('renovaciones_count', models.PositiveSmallIntegerField(default=0, verbose_name='Número de renovaciones')),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base imponible')),
                ('iva_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('tasas_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tasas DGT (exento)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total factura')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre cliente')),
                ('client_dni', models.CharField(max_length=20, verbose_name='DNI cliente')),
                ('client_street', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('client_postal_code', models.CharField(blank=True, max_length=10, verbose_name='CP')),
                ('client_municipality', models.CharField(blank=True, max_length=100, verbose_name='Municipio')),
                ('client_province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('payments', models.ManyToManyField(blank=True, related_name='tax_invoices', to='students.payment', verbose_name='Pagos incluidos')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='students.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Factura Trimestral',
                'verbose_name_plural': 'Facturas Trimestrales',
                'ordering': ['-year', '-quarter', '-invoice_number'],
                'indexes': [models.Index(fields=['year', 'quarter'], name='students_ta_year_599665_idx'), models.Index(fields=['student', '-fecha'], name='students_ta_student_75b985_idx')],
            },
        ),
    ]
